<?php

namespace AppBundle\Repository;

/**
 * RecordRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecordRepository extends \Doctrine\ORM\EntityRepository
{
    public function getFirst10(){
        $qb = $this->createQueryBuilder('r')
            ->setMaxResults(10)
            ->orderBy('r.score', 'DESC');
        return $qb->getQuery()->getArrayResult();
    }
}
